### PR TITLE
svlog: Forward declaration syntax support

### LINKED ISSUE #201: svlog: Implement parsing for struct/union forward declarations
Failing sv-tests:
* https://symbiflow.github.io/sv-tests/#moore_parse|7.2|struct_test_0
* https://symbiflow.github.io/sv-tests/#moore_parse|7.3|union_test_0

These tests create forward declarations for unions and structs using `typedef`, then later provide definitions. Example test (struct variant):

```
typedef struct mystruct_fwd;
typedef struct { logic a; logic b; } mystruct_fwd;
```
I think that there are two parts to this - support for the `typedef struct mystruct_fwd;` syntax at all, and then a later pass to handle the resolution of merging the forward declaration with its definition once available.

The following implementation is an initial stab at the first part: replacing the `parse_typedef()` function in src/svlog/syntax/parser.rs with a version that can handle the syntax.

```
fn parse_typedef<'n>(p: &mut dyn AbstractParser<'n>) -> ReportedResult<Typedef<'n>> {
    let mut span = p.peek(0).1;
    p.require_reported(Keyword(Kw::Typedef))?;

    // Check for forward declaration of struct/union first
    let fwd_ident = match (p.peek(0).0, p.peek(1).0, p.peek(2).0, p.peek(3).0) {
        (Keyword(Kw::Struct), _, Semicolon, _) => {
            p.bump();
            parse_identifier_name(p, "type name")
        }
        (Keyword(Kw::Union), Keyword(Kw::Tagged), _, Semicolon) => {
            p.bump();
            p.bump();
            parse_identifier_name(p, "type name")
        }
        (Keyword(Kw::Union), _, Semicolon, _) => {
            p.bump();
            parse_identifier_name(p, "type name")
        }
        _ => {
            Err(())
        }
    };

    match fwd_ident {
        Ok(name) => {
            p.require_reported(Semicolon)?;
            span.expand(p.last_span());

            // Store the forward decl as an implicit type
            let ty = Type::new(span, TypeData {
                kind: TypeKind::new(span, ImplicitType),
                sign: TypeSign::None,
                dims: Vec::default()
            });

            Ok(Typedef::new(span, TypedefData {
                name: name,
                ty: ty,
                dims: Vec::default()
            }))
        }
        _ => {
            // Normal typedef case
            let ty = parse_explicit_type(p)?;
            let name = parse_identifier_name(p, "type name")?;
            let (dims, _) = parse_optional_dimensions(p)?;
            p.require_reported(Semicolon)?;
            span.expand(p.last_span());
            Ok(Typedef::new(span, TypedefData { name, ty, dims }))
        }
    }
}
```

[Note that the existing implementation is just the block in `// Normal typedef case`, all the additional logic is new]. This version passes `moore --syntax` for the two test cases linked above. A full compiler invocation will then result in

```
error: `myunion_fwd` is defined multiple times
  --> test.sv:10:37-48:
   |
   | typedef union { logic a; logic b; } myunion_fwd;
   |                                     ^^^^^^^^^^^
   = note: Previous definition of `myunion_fwd` was here:
  --> test.sv:8:15-26:
   |
   | typedef union myunion_fwd;
   |               ^^^^^^^^^^^
```

This is expected as there's still more work to do here. At this point, it's unclear if I'm using the right `Type` structure to handle this  (or if a new TypeKind should be created to explicitly handle declared-but-not-yet-defined Types) so that appropriate diagnostics can be emitted if no definition is found.

### PR DESCRIPTION
**Pull request by dicta**
Resolves #201 in a more complete way than the experiment I wrote in that issue.

Fixes (at least) the following currently failing tests from sv-tests:
https://symbiflow.github.io/sv-tests/#moore|6.18|typedef_test_0
https://symbiflow.github.io/sv-tests/#moore|6.18|typedef_test_22
https://symbiflow.github.io/sv-tests/#moore|7.2|struct_test_0
https://symbiflow.github.io/sv-tests/#moore|7.3|union_test_0

In general, this PR parses typedefs of the following forms:
* `typedef x;`
* `typedef (struct|enum|union|union tagged) x;`

These typedefs can occur multiple times for the same name 'x', and in the sv-tests examples, can appear both before and after the typedef that completely defines the type. The changes to the resolver handle these cases and ensure that
1. A complete definition will override a forward declaration, but not the other way around.
2. Two complete definitions of the same type name will still produce a compiler error.
3. Multiple forward declarations for the same type name may be present without raising errors.

Error cases not yet handled:
* Conflicting types in forward declarations, i.e. code of the form `typedef struct x;` followed by a definition `typedef int x;` I think the information now present in the AST to resolve these for the struct/union cases but it doesn't yet check.
* Compiler does not error if there is a forward declaration without a corresponding definition. Is there a complete typecheck pass to hook into that happens after parsing? I wrote the code such that if a definition of TypeKind `ForwardType` is present after the resolver runs, that should indicate this error condition.  Generating this error is tested by (http://192.168.200.4:4444/#moore|6.18|typedef_test_28).

### CODE REVIEW

File: src/svlog/syntax/ast.rs [hunk 1]
```diff
@@ -760,6 +760,11 @@ pub enum TypeKind<'a> {
         name: Spanned<Name>,
     },
 
+    // Forward declarations
+    ForwardType {
+        kind: Box<TypeKind<'a>>,
+    },
+
```
Comment (fabianschuiki) [inline src/svlog/syntax/ast.rs:767]: Excellent idea to have this as a separate marker type kind.

File: src/svlog/resolver.rs [hunk 2]
```diff
@@ -737,16 +737,36 @@ impl<'a, 'c, C: Context<'a>> ScopeGenerator<'a, 'c, C> {
...
+            // where a "forward" declaration actually comes after the definition, which
+            // is apparently not an error in svlog.
+            if let DefNode::Ast(node) = def.node {
+                if let ast::AllNode::Typedef(ast) = node.as_all() {
+                    if let ast::ForwardType { kind: _ } = ast.ty.kind.data {
+                        return;
+                    }
+                }
+            }
+
```
Comment (fabianschuiki) [inline src/svlog/resolver.rs:769]: I like this approach, because it basically gets rid of forward declarations whenever an actual definition is encountered, such that *any* forward declaration being produced as the result of a name resolution indicates that no definition has been provided. Pretty neat.

File: src/svlog/typeck.rs [hunk 3]
```diff
@@ -670,6 +670,13 @@ pub(crate) fn packed_type_from_ast<'a>(
             packed_type_from_def(cx, def, name.span, env)
         }
 
+        // Forward declarations
+        ast::ForwardType { kind: _ } => {
+            // TODO This should likely be a nicer error if we get here because a forward
+            // declaration is not later defined.
+            bug_span!(ast.span(), cx, "type {:#1?} not implemented", ast.kind)
+        }
+
```
Comment (fabianschuiki) [inline src/svlog/typeck.rs:679]: I think it's okay to just trigger a `bug_span!` here: Technically the `ast::ForwardType` marker should never make its way into `packed_type_from_ast` via any other means than type checking of a `typedef`. I'd rather suggest we add some code to the type computation of a `typedef` (one of the callers of this `packed_type_from_ast`) and -- if we detect a forward declaration -- issue a nice error about no definition having been provided. Let's do something like that in a future PR.

**Comment by fabianschuiki** [comment]
Looks good to me, thanks for the excellent contribution! Merging :+1:
